# Generated by Django 2.2.4 on 2019-12-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20191213_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_arrival',
            field=models.DateTimeField(),
        ),
    ]
